### ISSUE TITLE
DataBase is not imported

### ISSUE THREAD

**Issue by drakulitka** [harikt/dms-expressive-skeleton#1]
`ERROR 1071 (42000) at line 11: Specified key was too long; max key length is 767 bytes`

**Comment by harikt** [comment]
I think this is related to mysql : 

https://github.com/harikt/cli.expressive/blob/05b35eac0a36ae5f6b3b1c0896203362ef508cdf/src/Install/DmsInstallCommand.php#L103

```
Please enable innodb_large_prefix. See here https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix
```

Let me know if that fixes the problem.

**Comment by harikt** [comment]
Hey @drakulitka ,

Was you able to proceed or still stuck with it ?
